r"""Numbers the prose cites that no figure carries -> paper/body_text_numbers.tex

One \newcommand per number, for the paper's preamble to \input. A name is
<measure><District><Year>, the year in words because a LaTeX command name
holds letters only, and a value is printed as the paper prints a share: a
whole number, with "percent" left to the sentence.

    share<District><Year>       the district's share of the county, 1870-1930
    blackShare<District><Year>  the Black share of the district, 1870 and 1920
    genderCensusShareMembers    members whose gender comes from a census sheet
    raceAssumedShareMembers     members recorded White on no source's say

    Jefferson held \shareJeffersonEighteenSeventy{} percent of the county.

The {} keeps the space after the command. Every number the table gives is
written, whether or not the prose uses it yet.
"""
from decimal import ROUND_HALF_UP, Decimal

import paths

YEARS = {1870: "EighteenSeventy", 1880: "EighteenEighty", 1890: "EighteenNinety",
         1900: "NineteenHundred", 1910: "NineteenTen", 1920: "NineteenTwenty",
         1930: "NineteenThirty"}
def per_cent(part, whole) -> str:
    """A share as the paper prints it: a whole number, halves rounded up."""
    return str((Decimal(int(part)) * 100 / Decimal(int(whole))).quantize(0, ROUND_HALF_UP))


def member_shares() -> dict:
    """How members, not seat-years, are known: one row per person, by name.

    genderCensusShareMembers   share of all members whose gender comes from a
                                census sheet, the rest read from the press
    raceAssumedShareMembers    share of all members recorded White because no
                                source says otherwise
    """
    m = paths.read("members").drop_duplicates(subset="name")
    return {
        "genderCensusShareMembers": per_cent(m.gender_source.str.contains("census").sum(), len(m)),
        "raceAssumedShareMembers": per_cent((m.race_source == "assumed").sum(), len(m)),
    }


def numbers() -> dict:
    """Every command's name and value, in the order the file lists them."""
    d = paths.read("residents_by_district")
    out = {}
    for year, g in d.groupby("year"):
        for r in g.itertuples():
            out[f"share{r.district}{YEARS[year]}"] = per_cent(r.total, g.total.sum())
    for r in d[d.black.notna()].itertuples():
        out[f"blackShare{r.district}{YEARS[r.year]}"] = per_cent(r.black, r.total)
    out.update(member_shares())
    return out


def tex(values: dict) -> str:
    lines = ["% Generated by code/analysis/body_text_numbers.py from data/clean/.",
             "% Never edit by hand: bash run.sh rewrites it.", ""]
    for name, value in values.items():
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    paths.BODY_TEXT_NUMBERS.write_text(tex(numbers()))
