r"""Numbers the prose cites that no figure carries -> paper/body_text_numbers.tex

One \newcommand per number, for the paper's preamble to \input. A name is
<measure><District><Year>, the year in words because a LaTeX command name
holds letters only, and a value is printed as the paper prints a share: a
whole number, with "per cent" left to the sentence.

    share<District><Year>       the district's share of the county, 1870-1930
    blackShare<District><Year>  the Black share of the district, 1870

    Jefferson held \shareJeffersonEighteenSeventy{} per cent of the county.

The {} keeps the space after the command. A command the prose does not
call yet is marked in the file; tests.py checks the marks against
paper/arlington-bsap.tex.
"""
from decimal import ROUND_HALF_UP, Decimal

import pandas as pd

import paths

YEARS = {1870: "EighteenSeventy", 1880: "EighteenEighty", 1890: "EighteenNinety",
         1900: "NineteenHundred", 1910: "NineteenTen", 1920: "NineteenTwenty",
         1930: "NineteenThirty"}
# The commands paper/arlington-bsap.tex calls. Add a name when the prose
# starts using it; every other command is written marked as not yet cited.
CITED = set()
UNCITED = "% not yet cited in arlington-bsap.tex"


def per_cent(part, whole) -> str:
    """A share as the paper prints it: a whole number, halves rounded up."""
    return str((Decimal(int(part)) * 100 / Decimal(int(whole))).quantize(0, ROUND_HALF_UP))


def numbers() -> dict:
    """Every command's name and value, in the order the file lists them."""
    d = pd.read_csv(paths.RESIDENTS_BY_DISTRICT)
    out = {}
    for year, g in d.groupby("year"):
        for r in g.itertuples():
            out[f"share{r.district}{YEARS[year]}"] = per_cent(r.total, g.total.sum())
    jefferson = d[(d.year == 1870) & (d.district == "Jefferson")].iloc[0]
    out["blackShareJeffersonEighteenSeventy"] = per_cent(jefferson.black, jefferson.total)
    return out


def tex(values: dict) -> str:
    lines = ["% Generated by code/analysis/body_text_numbers.py from data/clean/.",
             "% Never edit by hand: bash run.sh rewrites it.", ""]
    for name, value in values.items():
        line = f"\\newcommand{{\\{name}}}{{{value}}}"
        lines.append(line if name in CITED else f"{line}  {UNCITED}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    paths.BODY_TEXT_NUMBERS.write_text(tex(numbers()))
