r"""The roster the data appendix prints -> paper/members_roster.tex

One row per person who has served, in the order they first took a seat, with
the gender, race and birth year the report uses for each and a mark saying
what the value rests on. The paper \input{}s the file inside its own table
environment; this writes only the rows, so the heading, the notes and the
type size stay in the paper where the other tables keep theirs.

    \roster{Member}{Served}{Seated by}{Born}{Gender}{Race}

The marks, which the paper's note explains: \textsuperscript{c} a census
sheet, \textsuperscript{p} the press or a published profile,
\textsuperscript{a} assumed because no source says otherwise; a value that
rests on both a census sheet and the press carries both, c then p, as
\textsuperscript{c,\,p}, and is
never also marked assumed; a dash where no source gives the value. Rows fall
in groups by the decade of first seating, each under a bold heading;
\rosterk is a row the page may not break after, used so that no group leaves a
single row alone at the foot or head of a page. The design is Sally's choice among four prototypes
(4 October 2026); the roster and the evidence behind each cell are
data/clean/members.csv.
"""
import pandas as pd

import paths

MARK = {"census": "c", "press": "p", "assumed": "a"}
SEATED = {"election": "election", "appointment": "appointment",
          "special election": "special election", "unrecorded": "---"}


def basis(source) -> list:
    """The kinds of source a value rests on, in the fixed order census, press:
    census if any citekey begins with census, press if any other citekey is
    present. Assumed only when the column is exactly "assumed", so a value is
    never both assumed and sourced. Empty when nothing gives the value."""
    s = "" if pd.isna(source) else str(source).strip()
    if s in ("", "unsourced"):
        return []
    if s == "assumed":
        return ["assumed"]
    keys = [k.strip() for k in s.split(";") if k.strip()]
    kinds = []
    if any(k.startswith("census") for k in keys):
        kinds.append("census")
    if any(not k.startswith("census") for k in keys):
        kinds.append("press")
    return kinds


def marked(value, source) -> str:
    if pd.isna(value):
        return "---"
    v = str(int(value)) if isinstance(value, float) else str(value)
    marks = ",\\,".join(MARK[k] for k in basis(source))
    return v + (r"\textsuperscript{%s}" % marks if marks else "")



def rows(members: pd.DataFrame) -> list:
    """One (member, years, seated, born, gender, race) tuple per person, in
    the order of first seating. Years run from the first term's start to the
    last term's end, left open for a term that runs past the last year the
    seat table covers."""
    present = paths.read("members_by_year").year.max()
    out = []
    ordered = members.sort_values(["start_year", "start_month"], kind="stable")
    for name, g in ordered.groupby("name", sort=False):
        g = g.sort_values(["start_year", "start_month"])
        first, last = g.iloc[0], g.iloc[-1]
        years = f"{int(first.start_year)}--"
        if last.end_year < present:
            years += str(int(last.end_year))
        out.append((name, years, SEATED[first.seated_by],
                    marked(first.birth_year, first.birth_year_source),
                    marked(first.gender, first.gender_source),
                    marked(first.race, first.race_source),
                    int(first.start_year) // 10 * 10))
    return out


def tex(table: list) -> str:
    """The \\roster lines, a bold \\rosterdecade heading (1870s, 1880s, ...) above
    each decade's group, and \\rosterk (no page break after) on a group's first row and
    on the row before its last, so a break never strands one row."""
    esc = lambda s: s.replace("&", r"\&")
    # No blank line after the comments: inside the longtable a blank line is a
    # \par at the start of the first cell, and the heading's \multicolumn then
    # finds the cell already begun.
    lines = ["% Generated by code/analysis/members_roster.py from data/clean/members.csv.",
             "% Never edit by hand: bash run.sh rewrites it."]
    decades = sorted({r[-1] for r in table})
    for d in decades:
        group = [r[:-1] for r in table if r[-1] == d]
        head = r"\rosterheading" if d == decades[0] else r"\rosterdecade"
        lines.append(head + "{%ds}" % d)
        for i, r in enumerate(group):
            keep = len(group) > 1 and i in (0, len(group) - 2)
            cmd = r"\rosterk" if keep else r"\roster"
            lines.append(cmd + "".join("{%s}" % esc(c) for c in r))
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    members = paths.read("members")
    table = rows(members)
    assert len(table) == members.name.nunique()
    paths.MEMBERS_ROSTER.write_text(tex(table))
