r"""Which document names the Board in which years, and how many members each
stretch of years holds -> paper/members_by_source.tex

A roadmap for someone rebuilding the roster, not a figure. Each row is a
stretch of years, the document to open first for it, the documents to read
beside it, and the number of members who held a seat in any month of the
stretch. A member who served across a boundary between two stretches counts
in both, so the counts need not sum to the number of people who have served.
The stretches follow what the four rosters cover, not how any term in
`data/clean/members.csv` happens to cite them.

    \sourcerow{1870--1911}{Historical Society list}{O'Leary}{36}
"""
import paths

# (first year, last year or None for the present, document to open first,
# documents to read beside it). The edges are where a roster starts or stops
# naming the Board: the list names all three seats from 1912; Novack begins
# with the first Board elected at large in 1932 and ends in 1994; the County's
# candidate history runs to 2021 and the state's election results continue it.
STRETCHES = [
    (1870, 1911, "Historical Society list", "O'Leary"),
    (1912, 1931, "Historical Society list", "O'Leary to 1920"),
    (1932, 1994, "Novack", "County roll"),
    (1995, None, "County roll", "County candidate history; state election results"),
]


def members_in(members, first, last) -> int:
    """Members with a term that held a seat in any month from January of
    `first` through December of `last`. `held_from` and `held_to` count
    months from year 0 with the end exclusive, as data/clean/members.csv
    writes them."""
    lo = first * 12
    hi = (last + 1) * 12 if last is not None else float("inf")
    held = members[(members["held_from"] < hi) & (members["held_to"] > lo)]
    return int(held["name"].nunique())


def member_counts(members) -> list:
    return [members_in(members, first, last) for first, last, _, _ in STRETCHES]


def years(first, last) -> str:
    return f"{first}--{last}" if last is not None else f"{first}--present"


def tex(counts: list) -> str:
    out = ['% Generated by code/analysis/members_by_source.py from data/clean/members.csv.\n',
           '% Never edit by hand: bash run.sh rewrites it.\n']
    for (first, last, opens, beside), n in zip(STRETCHES, counts):
        out.append(r"\sourcerow{%s}{%s}{%s}{%d}" % (years(first, last), opens, beside, n) + "\n")
    return "".join(out)


if __name__ == "__main__":
    members = paths.read("members")
    counts = member_counts(members)
    assert members_in(members, STRETCHES[0][0], None) == members["name"].nunique(), (
        "a member's term falls outside every stretch - the stretches no longer cover the roster")
    paths.MEMBERS_BY_SOURCE.write_text(tex(counts))
