r"""The roster the data appendix prints -> paper/members_roster.tex

One row per person who has served, in the order they first took a seat, with
the gender, race and birth year the report uses for each and a mark saying
what the value rests on. The paper \input{}s the file inside its own table
environment; this writes only the rows, so the heading, the notes and the
type size stay in the paper where the other tables keep theirs.

    \roster{Member}{Years}{Seated by}{Gender}{Race}{Born}

The marks, which the paper's note explains: \textsuperscript{c} a census
sheet, \textsuperscript{p} the press or a published profile,
\textsuperscript{a} assumed because no source says otherwise; a dash where no
source gives the value. The design is Sally's choice among four prototypes
(4 October 2026); the roster and the evidence behind each cell are
data/clean/members.csv.
"""
import pandas as pd

import paths

MARK = {"census": r"\textsuperscript{c}", "press": r"\textsuperscript{p}",
        "assumed": r"\textsuperscript{a}", "none": ""}
SEATED = {"election": "elected", "appointment": "appointed",
          "special election": "special election", "unrecorded": "not recorded"}


def basis(source) -> str:
    """What a value rests on, read from its source column: a census citekey,
    the assumed marker, nothing, or any other citation, which is the press or
    a published profile."""
    s = "" if pd.isna(source) else str(source)
    if s in ("", "unsourced"):
        return "none"
    if s == "assumed":
        return "assumed"
    if "census" in s:
        return "census"
    return "press"


def marked(value, source) -> str:
    if pd.isna(value):
        return "---"
    v = str(int(value)) if isinstance(value, float) else str(value)
    return v + MARK[basis(source)]


def rows(members: pd.DataFrame) -> list:
    """One (member, years, seated, gender, race, born) tuple per person, in
    the order of first seating. Years run from the first term's start to the
    last term's end, left open for a term that runs past the last year the
    seat table covers."""
    present = paths.read("members_by_year").year.max()
    out = []
    ordered = members.sort_values(["start_year", "start_month"], kind="stable")
    for name, g in ordered.groupby("name", sort=False):
        g = g.sort_values(["start_year", "start_month"])
        first, last = g.iloc[0], g.iloc[-1]
        years = f"{int(first.start_year)}--"
        if last.end_year < present:
            years += str(int(last.end_year))
        out.append((name, years, SEATED[first.seated_by],
                    marked(first.gender, first.gender_source),
                    marked(first.race, first.race_source),
                    marked(first.birth_year, first.birth_year_source)))
    return out


def tex(table: list) -> str:
    esc = lambda s: s.replace("&", r"\&")
    lines = ["% Generated by code/analysis/members_roster.py from data/clean/members.csv.",
             "% Never edit by hand: bash run.sh rewrites it.", ""]
    lines += [r"\roster{%s}{%s}{%s}{%s}{%s}{%s}" % tuple(esc(c) for c in r) for r in table]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    members = paths.read("members")
    table = rows(members)
    assert len(table) == members.name.nunique()
    paths.MEMBERS_ROSTER.write_text(tex(table))
