r"""Which source backs each term, and how many members each stretch covers
-> paper/members_by_source.tex

A member-by-member stretch, not a figure: `data/clean/members.csv` names a
citekey, or several, on every term's `source`. Each term falls into one of
five stretches by which of the four rosters it cites — O'Leary's electoral
history, the Historical Society's 1967 list, Novack's roster, the County's
roll and candidate history — and a member who served across a boundary
between two stretches counts in both, so the five counts need not sum to the
number of people who have served. The table carries no per-row marks; the
roster's own superscripts (Table~\ref{tab:roster}) are a different thing, the
source for a member's traits rather than for the term itself.

    \sourcerow{Historical Society list and O'Leary}{14}
"""
import paths

OLEARY = "oleary2010"
HISTSOC = "arlhist1967officials"
NOVACK = "novack1994"
COUNTY = ("arlingtonva2026members", "arlingtonelections2021")

# The order the appendix prints them in: earliest stretch first.
STRETCHES = ["O'Leary only", "Historical Society list and O'Leary",
             "list only", "Novack and County", "County"]


def stretch(source: str) -> str:
    """Which of the five stretches a term's source falls in. Every term in
    data/clean/members.csv cites at least one of the four rosters, so this
    never falls through; a term it cannot place is a new kind of source,
    not a term to drop silently."""
    s = "" if source != source else str(source)  # NaN is never found in a string
    novack, county = NOVACK in s, any(k in s for k in COUNTY)
    if novack or county:
        if novack and not county:
            raise ValueError(f"{source!r} cites Novack but no County source - "
                              "a fifth stretch (\"Novack only\") the table does not expect")
        return "Novack and County" if novack else "County"
    oleary, histsoc = OLEARY in s, HISTSOC in s
    if oleary and histsoc:
        return "Historical Society list and O'Leary"
    if histsoc:
        return "list only"
    if oleary:
        return "O'Leary only"
    raise ValueError(f"{source!r} cites none of O'Leary, the Historical Society, "
                      "Novack or the County")


def member_counts(members) -> dict:
    """Members with at least one term in each stretch, by stretch."""
    members = members.copy()
    members["stretch"] = members["source"].map(stretch)
    counts = members.groupby("stretch")["name"].nunique()
    return {s: int(counts.get(s, 0)) for s in STRETCHES}


def tex(counts: dict) -> str:
    out = ['% Generated by code/analysis/members_by_source.py from data/clean/members.csv.\n',
           '% Never edit by hand: bash run.sh rewrites it.\n']
    for s in STRETCHES:
        out.append(r"\sourcerow{%s}{%d}" % (s, counts[s]) + "\n")
    return "".join(out)


if __name__ == "__main__":
    members = paths.read("members")
    counts = member_counts(members)
    assert sum(counts.values()) >= members.name.nunique(), (
        "fewer stretch-members than members who have served - a term fell through stretch()")
    paths.MEMBERS_BY_SOURCE.write_text(tex(counts))
